# Assignment 3

Darian Soetanto (3296539)
Nashifa Muchtar (3296466)
Rory Timmerman (2846055)
Jana Klaric (2850478)
Kirk Preston (​​3294056)
Anna Liang (3306321)

## Introduction and Motivation

On May 6, 2022 the FBI announced a press release offering rewards to those who can give information that can lead to the identification of people related to the Conti ransomware variant transnational organized crime group [1]. They are responsible for various ransomware attacks across the globe. This includes attacks on government entities such as the Costa Rican government in 2022 [2], the Irish Health Services in 2021 [3] and many others including non-government entities [4]. These attacks, especially on health services, made Conti gain notoriety. They operate through means of providing service, the term is RaaS (Ransomware-as-a-Service) [5]. It roughly functions just like how a car rental works, a person lets you have your car, in this case the ransomware, and you pay the person for it depending on how much you've used it. 

In 2022 the gang's chat group leaked online after declaring support of the Russian Invasion of Ukraine [6]. The chat does not exactly identify who the people involved are, but helps determine how many people are involved, how the group works and the dynamic among the members. This report aims to identify several aspects regarding the leaked chat in hopes to be able to somewhat identify or get close to identifying the roles each person played in the group. This is done by reading through the chat and analyzing conversations in it. Although it is difficult to directly identify the person based on their usernames and given IPs, this investigation can help provide a picture of the organization through the roles of each member and relationships between the members.

## Methodology and results 

The file containing the translated leaked chats of the Conti ransomware group was given by our professor (Jair) as a csv file. By analyzing the data we shall try to answer some of the most basic questions one would have about ransomware groups. In the process we shall use jupyter notebook with pandas and matplotlib.

In [ ]:
import pandas as pd

from collections import Counter

**ASPECT 1 - SIZE OF THE RECORD**

In the file there are 60772 (indices start from 0) records of the participants of the group exchanging messages. The original text in Russian is preserved, followed by and English translation:

![](records.png)

Figure 1: The number of records

**ASPECT 2 - NUMBER OF USERS INVOLVED, AVERAGE NUMBER OF MESSAGES OF USERS**

In [ ]:
#load csv file
df = pd.read_csv('people_talking.csv')
#place no restirctions on size of file
pd.set_option('display.max_rows', 60771)
pd.set_option('display.max_columns', None)
#transfer usernames in a list
from_column_values = df['from'].tolist()

#count how many messages a username has sent
username_counts = pd.Series(from_column_values).value_counts()
print(username_counts)

#average number of messages per person
total_messages = sum(Counter(from_column_values).values())

avg=total_messages/len(username_counts)
print('Average number of messages per person is: ', avg)

#kinds of usernames - aspect 4
miscellaneous=[]
seti=set(from_column_values)
q3mcco35auwcstmt_count=0
for element in seti:
    if '@q3mcco35auwcstmt.onion' in element:
        q3mcco35auwcstmt_count+=1
    elif '@q3mcco35auwcstmt.onion' not in element:
        miscellaneous.append(element)


defender@q3mcco35auwcstmt.onion                                         8246
stern@q3mcco35auwcstmt.onion                                            4323
driver@q3mcco35auwcstmt.onion                                           3968
bio@q3mcco35auwcstmt.onion                                              3196
mango@q3mcco35auwcstmt.onion                                            3194
ttrr@conference.q3mcco35auwcstmt.onion                                  3122
veron@q3mcco35auwcstmt.onion                                            2955
hof@q3mcco35auwcstmt.onion                                              2389
bentley@q3mcco35auwcstmt.onion                                          1810
bloodrush@q3mcco35auwcstmt.onion                                        1798
tramp@q3mcco35auwcstmt.onion                                            1629
skippy@q3mcco35auwcstmt.onion                                           1610
grom@q3mcco35auwcstmt.onion                                             1200

Table 1: Number of messages per user

Here a simple code was executed to find out how many messages were sent by which user. From the table above we can see that the top 3 senders were: defender@q3mcco35auwcstmt.onion, stern@q3mcco35auwcstmt.onion and driver@q3mcco35auwcstmt.onion with 8246, 4323 and 3968 messages sent respectively. From the same code we can calculate the average message number per person which turns out to be 221.8 messages per person.

**ASPECT 3 - ROLES OF USERS**

In [ ]:
#!pip install openpyxl==3.1.2 #uncomment to run notebook#

In [ ]:
##rewriting the convos into a nicer file
#new_df = df[['from', 'to', 'body_en']]
#output_excel_path = 'convos.xlsx'
#new_df.to_excel(output_excel_path, index=False)

One might ask if the participants in a ransomware group all have the same ranking or if they have different roles. To read the captured conversations, we used a piece of code above to put the conversations in a neat excel sheet so that they're more readable: "convos.xlsx". The conversations are too extensive to analyze the functions of all participants so we limited ourselves to finding at least 5 roles.

From the provided conversation we can conclude that the user stern@q3mcco35auwcstmt.onion has some sort of a role that involves managing other peoples' salaries. This we can conclude from their conversation with defender@q3mcco35auwcstmt.onion in which they ask stern: "hello, send the salary pliz https://1ty.me/fVwTjia 0.03753407". 

Next we found that user pumba@q3mcco35auwcstmt.onion was in charge of something called "America", most likely one of the ransom cases. In his message he tell user tramp@q3mcco35auwcstmt.onion the following as the answer to the question "What should we do about America?": "write to them like that all your date 650GB is in archives, divided into parts. it takes a long time to get your files out. Well, then add that the dates have already given enough and so. so tomorrow we will start uploading if you don&#39;t pay. Let’s say they don’t pay, then I download the movie for 20-30 gigs and archive it by dividing it into parts and upload several parts with the publication))) even if they want to watch, they won’t fucking succeed. in this way the resonance will go and fucking it will not be clear whether the date is there or not. I don&#39;t think they want to take the risk and pay. But this will be only on one condition that they don’t know for sure that our servers were screwed up". He states what he wants to happen if a victim doesn't pay. He also ends the conversation with: "but just to choke them like they have already given a lot and we won’t give 4 more files, well, this is laughter in my opinion" 

Furthermore, we found the role of the user that sent the most messages, defender@q3mcco35auwcstmt.onion. In his conversation with zulas@q3mcco35auwcstmt.onion he discusses details of some code: "1. take the value in the first line up to the first separator | - it will be in my opinion the user name dXNlcg== 2. then we replace all occurrences of |dXNlcg== with |&lt;line feed&gt;dXNlcg==" It is most likely this person is some sort of a chief coder in the group. Even though most of the messages he sent were encrypted, he did send the most in this file. This leads us to believe his position as chief and the conversation mentioned above indicates his position has to do with coding:

![](convo_defender.png)

Figure 2: Defenders chat with Zulas

Next, a role of user hash@q3mcco35auwcstmt.onion was found in the following conversation: 

![](hash_convo.png)

Figure 3: Hash's chat with rozetka

From this we have conclude that the mentioned user distributed attacks. They ask about how many files they should make, then they say that the "encoder and loader are needed" for something which might be specific malware they're developing.

Next, we have user bentley@q3mcco35auwcstmt.onion in which he has chats with multiple different users. Most of these chats includes him sending the other users a dropfile links along with the password to access them if needed. Based on the chats, we can tell that this user creates some sort of software or crypts according to the clients demands and needs. Here we can see a snippet of some of the conversations to and from bentley@q3mcco35auwcstmt.onion.

![](bentley.png)

Figure 4: Conversations to and from bentley@q3mcco35auwcstmt.onion

**ASPECT 4 - USERNAME DOMAINS**

For this aspect we shall analyze which domains of usernames are present in the chat. Our hypothesis is that they are all @q3mcco35auwcstmt.onion domain, but this shall be made sure of by the use of code:

In [ ]:
print("The amount of the q3mcco35auwcstmt.onion domain: ",q3mcco35auwcstmt_count)
print("The amount of users: ",len(username_counts))
print('Here are the ones not using the most frequent domain: ')
print('\n')
for i in range(len(miscellaneous)):
    print(miscellaneous[i])
    print('\n')

The amount of the q3mcco35auwcstmt.onion domain:  250
The amount of users:  274
Here are the ones not using the most frequent domain: 


alter


salmon21@thesecure.biz


admin@expiro-team.biz


ttrr@conference.q3mcco35auwcstmt.onion


eleos@msjb.pw


mango@odw5mdwotufuxxrgw3pvqjjuze3e33bylylkl667h4nefwiimwqsumyd.onion


eleoslin@msjb.pw


rozetka


b2zbrzj5sljbmemgfqnn7zlarduyjhvjwt


joynses@thesecure.biz


poll@conference.q3mcco35auwcstmt.onion


firefox333@xmpp.jp


q3mcco35auwcstmt.onion


packman@hsfhksrd62ga3n3v.onion


exploit.im


zevs@3mcco35auwcstmt.onion


odw5mdwotufuxxrgw3pvqjjuze3e33bylylkl667h4nefwiimwqsumyd.onion


hookahplace@conference.q3mcco35auwcstmt.onion


werka@conference.q3mcco35auwcstmt.onion


verchunls@chatterboxtown.us


buza


btdpnqwg2nqkqceetqnn7zlarduyjhvjwt


mitzi@6ub5waskpuglkrjbz5se23xushqvr3pgpseyetxiycjmp6h5gm6jrpad.onion


born@6ub5waskpuglkrjbz5se23xushqvr3pgpseyetxiycjmp6h5gm6jrpad.onion




Table 2: Domains of usernames

As it can be seen from above table, not all users belong to the same domain. Even though 250 out of 274 do have the q3mcco35auwcstmt.onion domain, 24 others do not. The examples of other domains that aren't .onion are: @thesecure.biz, @chatterboxtown.us and @expiro-team.biz. These 3 seem to have normal words inside them, other miscellaneous domains are made out of random letters and are most likely made to be discarded. We have tried searching up these domains on chat GPT and online and here's what we found:

![](biz.png)

Figure 5: searching up @thesecure.biz, by the use of [7]

It was found that the domain name is based in Russia and it enables people to have secure chats between them and their business partners. 

![](chatbox.png)

Figure 6: @chatterbox.us domain result

The results of @expiro-team.biz couldn't be found anywhere but we suppose that it is somewhat similar to the @thesecure.biz since they have the same extension - .biz.

**ASPECT 5 - IP-ADDRESSES IN THE DATA AND THEIR USES**

In [ ]:
import pandas as pd
import re

# Load data
df = pd.read_csv('people_talking.csv')

# IPv4 address pattern
ip_pattern = r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'

# Extract IP addresses from text
def extract_ip(text):
    ip_addresses = re.findall(ip_pattern, text)
    return ','.join(ip_addresses) if ip_addresses else None

# Select relevant column and delete empty entries
df['IP_Addresses'] = df.iloc[:, 5].apply(extract_ip)
df = df.dropna(subset=['IP_Addresses'])

# Print all IP Addresses with their row number (csv) and keep track of the unique ones
unique_addresses = set()
for index, row in df.iterrows():
    IPA = row['IP_Addresses']
    print(f"Row {index + 2}: IP Addresses - {IPA}")
    unique_addresses.add(IPA)
total_unique_addresses = len(unique_addresses)
print(f"Total Unique IP Addresses Found: {total_unique_addresses}")

Row 1068: IP Addresses - 208.110.64.130,61.177.172.13,61.177.172.13,208.110.64.130,208.110.64.130,192.187.107.16,192.187.107.16,208.110.64.130,91.189.92.20,91.189.92.38,91.189.92.39,91.189.92.19,91.189.92.40,91.189.92.40,91.189.92.41,208.10.64.130,208.110.64.130,193.57.40.49,208.110.64.130,185.191.34.120,208.110.64.130,193.27.228.65,208.110.64.130,208.110.64.130,185.191.34.120,71.168.131.157,208.10.64.130,208.110.64.130,193.27.228.65,208.110.64.130,208.110.64.130,208.110.64.130,193.57.40.49,208.110.64.130,71.168.131.157,208.110.64.130,71.6.199.23,208.110.64.130,161.35.12.145
Row 1162: IP Addresses - 46.8.157.223
Row 1714: IP Addresses - 217.12.218.109,217.12.203.191
Row 2169: IP Addresses - 73.180.36.152,208.125.46.162
Row 2424: IP Addresses - 5.181.156.166,94.140.115.123,103.124.104.56,194.135.33.150,5.181.80.121,185.99.133.115,89.41.182.52,193.8.172.239,194.15.113.92,5.196.197.27,162.55.32.162,31.13.195.184
Row 2433: IP Addresses - 192.168.86.23,255.255.255.0,192.168.86.1,192.168.86.

In most conversations these IP-addresses are used to 

- share attack protocols

- as part of personal data of a victim

- share access to a machine or network (possibly sold)

- access the admin panel (e.g. of an attack)

**ASPECT 6 - EXAMPLES OF URLs IN THE DATA AND WHAT THEY ARE FOR**

The following data was obtained by searching for the keyword ".com" and manually looking through the body_en column of the convos.xlsx file. 

There were several 'Privnote' URLs shared between them, for example: https://privnote.com/bHoPj0QF#1lNBQyn7S . This website is used to send notes that will destroy themself after being read, it it may have been used by the group to send larger bodies of text that were not suitable to send via the chat. 

![](modnik.png)

There were also several 'SendSpace' URLs shared between them, for example: https://www.sendspace.com/file/5dyime. This website is used to send large files between members via link. There is no requirement for an account to be made so it was mostly likely used for the convenience and anonymity of the service.

![](netwalker.png)

The members also send links of companies to target, shown in the screenshot below. In this specific example, it seems a leader is assigning someone to conduct and initial investigation on the companies henry.com, zimmer-group.com, diodes.com and promedmolding.com. Earlier on in the chat, several other companies are also mentioned, including pfizer.com. 

![](figure7.png)

Figure 7: companies to target

**ASPECT 7 - YAHOO ACCOUNTS AND  USAGE**

The data had no direct mentions of any account ending in '@yahoo.com'. But after further investigation, one user nevada@q3mcco35auwcstmt.onion mentions that they create multiple emails accounts to send phishing emails and to collect credit card information, including a Yahoo account. They also include a print screen link sharing their account. 

![](yahoo.png)

**ASPECT 8 - BITCOIN WALLETS**

This is a script that analyses the text in the .csv file for all text that has the correct BitcoinIP addresses address pattern

In [ ]:
import pandas as pd
import re

# Load data
df = pd.read_csv('people_talking.csv')

# Bitcoin wallet pattern
bitcoin_wallet_pattern = r'\b(1|3)[A-HJ-NP-Za-km-z1-9]{25,34}\b'

# Function to extract Bitcoin wallet addresses from a text
def extract_bitcoin_wallet(text):
    match = re.search(bitcoin_wallet_pattern, text)
    return match.group(0) if match else None

# Select relevant columns and delete empty entries
df['Bitcoin_Wallets'] = df.iloc[:, 5].apply(extract_bitcoin_wallet)
df['Username'] = df.iloc[:, 2]
df = df.dropna(subset=['Bitcoin_Wallets'])

# Print the Bitcoin wallet addresses found and keep track of the unique ones
unique_wallets = set()
for index, row in df.iterrows():
    bitcoin_address = row['Bitcoin_Wallets']
    username = row['Username']
    print(f"Row {index + 2}: Bitcoin Address - {bitcoin_address}, Username - {username}")
    unique_wallets.add(bitcoin_address)
total_unique_addresses = len(unique_wallets)
print(f"Total Unique Bitcoin Addresses Found: {total_unique_addresses}")


Row 9: Bitcoin Address - 3ESoHHu87mTrFNSNUaMVEfT3vYwRYGfSHQ, Username - tom@q3mcco35auwcstmt.onion
Row 94: Bitcoin Address - 3ESoHHu87mTrFNSNUaMVEfT3vYwRYGfSHQ, Username - many@q3mcco35auwcstmt.onion
Row 98: Bitcoin Address - 3ESoHHu87mTrFNSNUaMVEfT3vYwRYGfSHQ, Username - tom@q3mcco35auwcstmt.onion
Row 312: Bitcoin Address - 1PemRXvQ5nbDs6q19pCUzfd4kXVGovVoe3, Username - salamandra@q3mcco35auwcstmt.onion
Row 325: Bitcoin Address - 1PemRXvQ5nbDs6q19pCUzfd4kXVGovVoe3, Username - salamandra@q3mcco35auwcstmt.onion
Row 563: Bitcoin Address - 3ESoHHu87mTrFNSNUaMVEfT3vYwRYGfSHQ, Username - many@q3mcco35auwcstmt.onion
Row 1167: Bitcoin Address - 3ESoHHu87mTrFNSNUaMVEfT3vYwRYGfSHQ, Username - many@q3mcco35auwcstmt.onion
Row 2186: Bitcoin Address - 14HnaQfsQdtgVSNR91jLcbcKtdyddDfP6D, Username - bentley@q3mcco35auwcstmt.onion
Row 2194: Bitcoin Address - 14HnaQfsQdtgVSNR91jLcbcKtdyddDfP6D, Username - bentley@q3mcco35auwcstmt.onion
Row 2265: Bitcoin Address - 15gjb8F5Zd8XRKBCgVxsr8ZuVzr7yBtnCN, Use

Table 3: Bitcoin wallets and owners

**ASPECT 9 - EXAMPLES OF INTERESTING CONVERSATIONS**

Below are the screenshots of three interesting conversations:

The first figure in this aspect is interesting because it shows the logic behind how ransomware groups are thinking. The more they show they are willing to negotiate or even correspond with their victims, the more the parties become humanized to each other, thus losing ground in demanded payment amounts. Ransomware groups maximize their profits when their attack is swift, and decapitating, and the victims capitulate rapidly.

The second figure hints at the group being aware that the FBI is onto their activities, adjacent activities, or a case. What is more interesting is that on the top lines of the figure, one of the chat participants is alluding to connections within the legal system that he might be able to exploit. If the group is not able to exploit these opportunities, they definitely know enough about certain individuals to be able to give themselves advanced notice to stay under the radar.

The third figure highlights the command and control of the group. The Defender character and the Stern character appear to be the leadership or managers of the group. As such they are responsible for the upkeep of software that users within their organization use to maintain their illicit activities. Whenever either the Defender character or the Stern character speaks, the group is going to listen.

![](figure8.png)

Figure 8. Negotiation logic with victims

![](figure9.png)

Figure 9. Criminal insights into certain people in the legal system

![](figure10.png)

Figure 10. Command and Control of the group via Stern and Defender

**ASPECT 10 - EXAMPLES OF COMPLAINING**

Below are the screenshots of three moments of complaining:

![](figure11.png)

Figure 11. Complaints about salary raises and incompetent work on infrastructure.

![](figure12.png)

Figure 12. Complaints about the perceived incompetence of one of the group members. 

![](figure13.png)

Figure 13. Complaints about Botnet services and inept team members.

**ASPECT 11 - HOW MUCH THEY EARN**

Currently, all of the Bitcoin wallets found have a balance of 0. However, within the transcripts, there were multiple offers that were agreed to. The highest offer currently found was on line 22,276 of the Excel convos file. Bio Character was demanded to pay Skippy Character's 2,300,000 USD in BTC. Further conversation on line 40,135 of the same file shows that after negotiation, Skippy Character reduced his demands to 1,150,000 USD to be paid in BTC. This is the highest amount found during a cohesive set of negotiations. There were other offers found that totaled around 1,000,000 USD. At the very least, the group likely earned 1,150,000 USD in BTC to be dispersed into any of the wallets that they controlled.

**ASPECT 12 - THREE CONVERSATIONS WORTH INVESTIGATING FURTHER**

Below are three figures that highlight some of the interesting conversations present in the correspondence. The first figure highlights the Stern character as one of the managers of the group. His character should be further investigated that way his role within the criminal organization can be better understood, especially if he can be tracked down in person. The second figure highlights the ransomware group's desire to create their own cryptosystem using different crypto software. Understanding how these pieces of crypto software work could allow law enforcement to find additional ways to embed themselves in the infrastructure and intercept communication. The third figure highlights the other managerial character, the Defender character and his interest in upkeeping the Toad software. Understanding the software that groups utilize allows law enforcement to get a better idea of the inner workings of groups, such as gleaning insights on how pieces of software fit together.

![](figure14.png)

Figure 14. Stern character serving as the manager of the group.

![](figure15.png)

Figure 15. The Ransomware group is interested in creating their own crypto system.

![](figure16.png)

Figure 16. Defender character managing software upkeep which highlights critical software for ransomware group.

**ASPECT 13 - NUMBER OF ENCRYPTED MESSAGES**

There were 14,374 encrypted messages sent that could not be decrypted. Given there are 60,772 total records, only 23.65% of messages were encrypted and could not be be read by law enforcement. If all group members sent encrypted messages, the group's information could have been protected and even if the conversation leaked (as it did) nobody would know what it said. A lot of these encrypted messages came from the defender user. As it was mentioned before, we suppose he is some sort of a chief coder within the group. It is likely that the messages that he sent that were encrypted are pieces of encrypted code (not all of them, but some could be).

**ASPECT 14 - NUMBER OF HOURS ACTIVE PER USER**

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/NorthwaveSecurity/complete_translation_leaked_chats_conti_ransomware/main/jabber_chat_2021_2022_translated.csv"
df14 = pd.read_csv(url)
df14['ts'] = pd.to_datetime(df14['ts'])
user_activity_span = df14.groupby('from')['ts'].agg(['min', 'max'])
user_activity_span['time active (hours)'] = (user_activity_span['max'] - user_activity_span['min']).dt.total_seconds() / 3600
user_activity_hours = user_activity_span[['time active (hours)']].sort_values(by='time active (hours)', ascending=False)
user_activity_hours


time active (hours)
from                                                                   
baget@q3mcco35auwcstmt.onion                                9490.990288
pin@q3mcco35auwcstmt.onion                                  9436.322861
hash@q3mcco35auwcstmt.onion                                 9431.501696
terry@q3mcco35auwcstmt.onion                                9423.978492
defender@q3mcco35auwcstmt.onion                             9406.344568
vampire@q3mcco35auwcstmt.onion                              9397.312151
kagas@q3mcco35auwcstmt.onion                                9397.054112
green@q3mcco35auwcstmt.onion                                9349.018803
mango@q3mcco35auwcstmt.onion                                9342.953595
grant@q3mcco35auwcstmt.onion                                9338.708579
stern@q3mcco35auwcstmt.onion                                9315.256512
dandis@q3mcco35auwcstmt.onion                               9287.573187
bentley@q3mcco35auwcstmt.onion                              9244.367428
van@q3mcco35auwcstmt.onion                                  9244.333506
modnik@q3mcco35auwcstmt.onion                               9233.377885
carter@q3mcco35auwcstmt.onion                               9213.096101
strix@q3mcco35auwcstmt.onion                                9201.235179
globus@q3mcco35auwcstmt.onion                               9168.900922
derek@q3mcco35auwcstmt.onion                                9143.509721
veron@q3mcco35auwcstmt.onion                                9082.295441
many@q3mcco35auwcstmt.onion                                 9070.125256
driver@q3mcco35auwcstmt.onion                               8922.971911
kent@q3mcco35auwcstmt.onion                                 8903.551461
rand@q3mcco35auwcstmt.onion                                 8873.722728
viper@q3mcco35auwcstmt.onion                                8862.706115
mentos@q3mcco35auwcstmt.onion                               8834.090867
braun@q3mcco35auwcstmt.onion                                8826.542503
ghost@q3mcco35auwcstmt.onion                                8792.950860
stakan@q3mcco35auwcstmt.onion                               8693.742357
love@q3mcco35auwcstmt.onion                                 8691.604891
hlor@q3mcco35auwcstmt.onion                                 8666.297448
revers@q3mcco35auwcstmt.onion                               8530.065772
bekeeper@q3mcco35auwcstmt.onion                             8450.284379
hors@q3mcco35auwcstmt.onion                                 8450.123048
flip@q3mcco35auwcstmt.onion                                 8426.699914
bourbon@q3mcco35auwcstmt.onion                              8374.026836
salamandra@q3mcco35auwcstmt.onion                           8327.269812
beta@q3mcco35auwcstmt.onion                                 8241.876634
buza@q3mcco35auwcstmt.onion                                 8239.925621
elon@q3mcco35auwcstmt.onion                                 8045.263486
azot@q3mcco35auwcstmt.onion                                 8022.103756
ganesh@q3mcco35auwcstmt.onion                               7992.923025
rozetka@q3mcco35auwcstmt.onion                              7989.800677
cruz@q3mcco35auwcstmt.onion                                 7987.623687
johnyboy77@q3mcco35auwcstmt.onion                           7958.195460
professor@q3mcco35auwcstmt.onion                            7806.557785
ali@q3mcco35auwcstmt.onion                                  7764.587478
leo@q3mcco35auwcstmt.onion                                  7759.676102
hof@q3mcco35auwcstmt.onion                                  7688.049052
merch@q3mcco35auwcstmt.onion                                7687.117867
zolotoy@q3mcco35auwcstmt.onion                              7402.044487
idgo@q3mcco35auwcstmt.onion                                 7390.878316
netwalker@q3mcco35auwcstmt.onion                            7367.523041
blackjob@q3mcco35auwcstmt.onion                             7359.530472
clipper@q3mcco35auwc

Table 4: Time of hours active

Although the number of hours each user is active does not directly correlate with their involvement in the scheme itself, we can say that they have more or less the most knowledge and is monitoring this whole scheme. For example, we have previously found that the user defender@q3mcco35auwcstmt.onion sent the most messages, however according to the table above, we can see that they rank 5th from the list. This shows that you can be the most active per number of messages but still not be the most active in terms of hours. The same goes for stern. Even though we suspect him to have a lot of responsibilities within the group because we hypothesize him to be some sort of a manager role within the group, there are many other users who seemed to be more active in the chat than him.

**ASPECT 15 - NUMBER OF MONTHLY MESSAGES**

By counting the number of monthly messages sent, it can be seen that November 2021 is the month with the most messages in a month at more than 8000 messages. Followed by October 2021 then December 2021 respectively. While the least amount of messages was sent on February 2021 and April 2021, disregarding January 2021 and February 2022 since records did not cover the whole month for those 2 months. In November 2021 the group conducted attacks notably on CS Energy and the Australian Government [4]. Whereas in October 2021 the group attacked Meyer Corporation, a cookware distributor, Graff, a Jewelry Company, JVC Kenwood, electronics company and in December of 2021, they continued to then attack multiple companies in multiple sectors including banking, hospitality and government [4]. The autumn of 2021 was the peak of their activities as can be seen from number of monthly messages and attack history [4].

![](month.png)

Figure 17: Number of monthly messages

**ASPECT 16 - DOMAIN CHANGE**

We have noticed that the ending of the csv file that we were given to analyze is somewhat weird to say the least. It contains a paragraph in Russian (non translated) and while its contents point to the fact that it is also a message. Actually, it is a message we encountered before just not in its entirety. Here's the translation made with Google Translate of the last paragraph:

![](ending.png)

Figure 18: The ending paragraph

This is a message about changing domains. It holds instructions on how to do it and even the standard port of the thing. It was probably broadcasted to everyone, or it might have been a notification that opened up when you opened the chat app. One way or another we suppose everyone was meant to see this message so they could change their domains. Because of this message, the FBI might be able to track down the new domain as well and shut it down.

## Conclusion

In conclusion, this csv file of about 60 000 messages reveals a lot about how a ransomware group works. By analyzing the file we have managed to identify the biggest players in the group. We found how many messages they sent, how many hours they stay active and what their roles are within the organization. An estimation of revenue of this group was made as well since the Bitcoin wallets got leaked with the messages (wallet numbers were exchanged via messages). From there who owns which wallet wasn't hard to identify. The most suspicious conversations were highlighted as well as the conversations that gave us insight on what the logic behind negotiations is. 

One set of leaked messages can change the whole scheme of things for a ransomware group because if it was so simple for a couple of students to analyze their conversations, one might wonder how much information FBI got out of this file. This file shows how they think, how they operate (there are roles), how they transfer money to each other etc. The group could have avoided this by using encrypted messages. Then the results wouldn't have been this easy to analyze. 

In conclusion, if a normal person like us would have one day stumbled upon this leaked chat and had been the first analyze it (faster than FBI), they might have been rewarded an substantial amount of money for something we had to do for homework :).

## References

[1] Reward Offers for Information to Bring Conti Ransomware Variant Co-Conspirators to Justice. Retrieved from: https://www.state.gov/reward-offers-for-information-to-bring-conti-ransomware-variant-co-conspirators-to-justice/   

[2] President Rodrigo Chaves says Costa Rica is at war with Conti hackers. Retrieved from: https://www.bbc.com/news/technology-61323402 

[3] Irish cyber-attack: Hackers bail out Irish health service for free. Retrieved from: https://www.bbc.com/news/world-europe-57197688   

[4] All About Conti Ransomware. Retrieved from: https://www.securin.io/articles/all-about-conti-ransomware/

[5] The Rise and Fall of the Conti Ransomware Group. Retrieved from: https://globalinitiative.net/analysis/conti-ransomware-group-cybercrime/

[6] Conti ransomware gang’s internal chats leaked online after declaring support for Russian invasion. Retrieved from: https://techcrunch.com/2022/02/28/conti-ransomware-chats-leaked/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAGlWN205uJmOd_2i2ImWg52w7_iB2HsXtHS4EBKFUhDWqJ_A-UtHyDeTWfQHZrZAiqsVkGg8h_2pbrouOOA5-Za02cW9yzHQfR7GbXcrhWS9Hjey1PyAL2yWSkkT8Q67zZdOeWChK7dInuvBINYb9fnq9Id28FrwTmztzJ9O1KZ4

[7] Urlscan.io, online: https://urlscan.io/

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=411e6c34-0039-4fc2-86a3-93ef8e39f129' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>